-- return {
--
--   "hoob3rt/lualine.nvim",
--   config = function()
--     local status = require("nvim-spotify").status
--     status:start()
--     require("lualine").setup({
--       sections = {
--         lualine_x = {
--           status.listen,
--         },
--       },
--       options = {
--         -- theme = 'gruvbox', -- Cambia el tema si lo deseas
--         section_separators = { left = "", right = "" },
--         component_separators = { left = "", right = "" },
--       },
--     })
--   end,
-- }
